AllCops:
  DisplayCopNames: true

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
    '%W': '[]'

Metrics/AbcSize:
  Max: 18

Metrics/MethodLength:
  Max: 18
